version: "2"

services:
    {%- for service in services: %}
    {{service['name']}}:
        container_name: {{service['name']}}
        image: {{service['image']}}
        restart: always
        {%- if 'extra_docker_args' in service: %}
        {%- for arg, value in service['extra_docker_args'].items() %}
        {%- if value is string: %}
        {{arg}}: {{value|yaml_encode}}
        {%- elif value is iterable: %}
        {{arg}}:
            {%- for item in value %}
            - {{item|yaml_encode}}
            {%- endfor %}
        {%- else: %}
        {{arg}}: {{value|yaml_encode}}
        {%- endif %}
        {%- endfor %}
        {%- endif %}
        {%- if 'mapped_ports' in service: %}
        ports:
            {%- for port in service['mapped_ports']: %}
            - {{port}}
            {%- endfor %}
        {%- endif %}
        {%- if 'environment' in service: %}
        environment:
            {%- for var in service['environment']: %}
            - {{var}}
            {%- endfor %}
        {%- endif %}
        {%- if 'volumes' in service: %}
        volumes:
            {%- for volume in service['volumes']: %}
            - {{volume}}
            {%- endfor %}
        {%- endif %}
        {%- if 'lan' in service: %}
        networks:
            - {{service['lan']}}
        {%- endif %}
    {%- endfor %}
networks:
    {%- for network in networks: %}
    {{network}}:
        driver: bridge
    {%- endfor %}
